image: debian/stable
packages:
  - curl
  - rsync
  - ruby
  - ruby-dev
  - zlib1g-dev
sources:
  - https://git.sr.ht/~timharek/timharek.no
enviroment:
  deploy: deploy@wyd.no
secrets:
  - aee38f85-a4a3-4081-a4c0-e96c6e721e7b
triggers:
  - action: email
    condition: always
    to: Tim Hårek Andreassen <tim@harek.dev>
tasks:
  - setup: |
      sudo gem install github-pages jekyll-textile-converter
      jekyll --version
  - build: |
      cd timharek.no
      jekyll build
  - deploy: |
      cd timharek.no
      sshopts="-4 -o StrictHostKeyChecking=no"
      rsync --rsh="ssh $sshopts" -rP _site/ ${deploy}:/var/www/timharek.no/html/
