image: alpine/edge
packages:
  - hugo
  - npm
  - rsync
environment:
  deploy: tim@vps.tukler.no
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
secrets:
  - 0323bc6f-a046-4b96-8496-2bac6e7ee107 # SSH
sources:
  - https://git.sr.ht/~timharek/timharek.no
triggers:
  - action: email
    condition: failure
    to: tim@harek.no
tasks:
  - setup: |
      echo 'cd timharek.no' >> ~/.buildenv
  - build: |
      npm i
      hugo
  - mirror: |
      git push --force --mirror git@github.com:timharek/timharek.no.git
      git push --force --mirror git@codeberg.org:timharek/timharek.no.git
  - deploy: |
      sshopts="ssh -o StrictHostKeyChecking=no"
      rsync --rsh="$sshopts" -avz --delete public/ $deploy:/var/www/timharek.no
      rsync --rsh="$sshopts" -avz --delete redirects $deploy:/var/www/timharek.no/redirects

