image: alpine/edge
packages:
  - deno
  - rsync
environment:
  deploy: tim@vps.tukler.no
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
secrets:
  - 0323bc6f-a046-4b96-8496-2bac6e7ee107
sources:
  - https://git.sr.ht/~timharek/timharek.no
triggers:
  - action: email
    condition: failure
    to: tim@harek.no
tasks:
  - setup: |
      echo 'cd timharek.no' >> ~/.buildenv
  - test: |
      deno test -A
      deno task check
  - check: |
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - mirror: |
      git push --force --mirror git@github.com:timharek/timharek.no.git
      # FIXME: There is a problem with Codeberg unless pushed after SSHing onto the failed build
      # git push --force --mirror git@codeberg.org:timharek/timharek.no.git
  - deploy: |
      git --no-pager log -1 --format=%ci > last_deploy
      sshopts="ssh -o StrictHostKeyChecking=no"
      rsync --rsh="$sshopts" -avrP --exclude "last_deploy" --exclude ".git" --exclude "node_modules" --exclude ".env*" --delete . $deploy:/var/www/timharek.no
      rsync --rsh="$sshopts" -avrP last_deploy $deploy:/var/www/timharek.no/last_deploy

