title: Tim Hårek
email: tim@harek.dev
description: >-
  I'm a developer from Norway. I care about creating solutions that respects people, in terms of privacy, security and user experience. 
url: "https://timharek.no"
sass:
    sass_dir: assets/_sass

primary_color: 0096F5

github_username: timharek
sourcehut_username: timharek
mastodon_instance: snabelen.no
mastodon_username: tim

plugins:
    - jekyll-feed
    - jekyll-json-feed
    - jekyll-target-blank
    - jekyll-redirect-from

exclude: 
    - start.sh
    - README.md
    - LICENSE

target-blank:
    add_css_classes: external
