title: Tim Hårek
email: tim@harek.dev
description: >-
    I'm a developer, dog-person, and hiker currently studying Computer Security @UiB. This is my corner on the interwebs, have a look around.
url: "https://harek.dev"
sass:
    sass_dir: assets/_sass

primary_color: 0096F5

github_username: timharek
linkedin_username: timhrek

plugins:
    - jekyll-feed
