title: Tim Hårek
email: tim@harek.dev
description: >-
  I'm a developer from Norway. I care about creating solutions that respects people, in terms of privacy, security and user experience. 
url: "https://timharek.no"
sass:
    sass_dir: assets/_sass

primary_color: 0096F5

social:
  github: timharek
  sourcehut: timharek
  mastodon:
    instance: snabelen.no
    name: tim

collections:
  projects:
    sort_by: date

include:
  - _pages

exclude: 
    - start.sh
    - README.md
    - LICENSE

####
# Plugins section
####
plugins:
    - jekyll-feed
    - jekyll-json-feed
    - jekyll-target-blank
    - jekyll-redirect-from

target-blank:
    add_css_classes: external

jekyll_compose:
  auto_open: true
  default_front_matter:
    posts:
      excerpt: 
      author: Tim Hårek
      tags: 
