title: Tim Hårek
email: tim@harek.dev
description: >- # this means to ignore newlines until "baseurl:"
    I'm a developer, something, and something. I'm currently studying Computer Security @UiB. This is my corner on the interwebs, have a look around.
url: "https://harek.dev"

primary_color: 0096F5
#twitter_username: jekyllrb
github_username: timharek
linkedin_username: timhrek

# Build settings
#theme: jekyll-theme-adipid
plugins:
    - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
