title: Tim Hårek
email: tim@harek.dev
description: >-
    I'm a developer, something, and something. I'm currently studying Computer Security @UiB. This is my corner on the interwebs, have a look around.
url: "https://harek.dev"

primary_color: 0096F5

github_username: timharek
linkedin_username: timhrek

plugins:
    - jekyll-feed
