base_url = "https://timharek.no"

title = "Tim Hårek"
description = """
Full-stack developer from Norway that cares about creating solutions that
respects people in terms of privacy, security and user experience."""

default_language = "en"

compile_sass = true
build_search_index = false
generate_feed = true
feed_filename = "rss.xml"

minify_html = true

taxonomies = [
  { name = "tags", feed = false },
]

[translations]
latest_posts = "Latest posts"
view_all = "View all"
published = "Published"
updated = "Updated"
show_all = "Show all"
source = "Source"
link = "Link"
last_deploy = "Last deploy"
toc = "Table of contents"
reply_via_email = "Reply via e-mail"
total_words_written = "Total words written"
total_post_published = "Total posts published"
average_word_post = "Average word per post"
first_post = "First post"
longest_post = "Longest post"
with = "with"
words = "words"
posts_words_per_year = "Posts/words per year"
year = "Year"
no_post = "No. of posts"
average_word = "Avg. words"
top_tags = "Top tags"
posts = "Posts"
tagged_with = "Tagged with"
also_mentioned_in = "Also mentioned in"

[languages.no]
title = "Tim Hårek"
taxonomies = [
  { name = "tags", feed = false },
]

[languages.no.translations]
latest_posts = "Siste innlegg"
view_all = "Se alle"
published = "Publisert"
updated = "Sist oppdatert"
show_all = "Vis alle"
source = "Kilde"
link = "Lenke"
last_deploy = "Siste bygging"
toc = "Innholdsfortegnelse"
reply_via_email = "Svar via e-post"
total_words_written = "Antall skrevne ord"
total_post_published = "Antall publiserte innlegg"
average_word_post = "Gjennomsnittlig antall ord"
first_post = "Første innlegg"
longest_post = "Lengste innlegg"
with = "med"
words = "ord"
posts_words_per_year = "Innlegg/ord per år"
year = "År"
no_post = "Antall innlegg"
average_word = "Gjennomsnittlig antall ord"
top_tags = "Topp tags"
posts = "Innlegg"
tagged_with = "Tagget med"
also_mentioned_in = "Også nevnt i"

[markdown]
highlight_code = true
highlight_theme = "one-dark"
external_links_target_blank = true
external_links_no_referrer = true
smart_punctuation = true

[extra]
author = "Tim Hårek Andreassen"
author_img = "img/me.jpeg"
email = "tim@harek.no"
date_format = "%F"
date_format_long = "%e. %B %Y"
logo = "img/logo.svg"
cover = "img/cover.png"

nav = [
  { path = "@/blog/_index.md" },
  { path = "@/work/_index.md" },
  { path = "@/connect/_index.md" },
  { path = "@/about/_index.md" }
]

footer_nav = [
  { path = "@/stats.md" },
  { path = "@/privacy.md" }
]

