# The URL the site will be built for
base_url = "https://timharek.no"

title = "Tim Hårek"
description = """
Full-stack developer from Norway that cares about creating solutions that
respects people in terms of privacy, security and user experience."""

default_language = "en"

compile_sass = true
build_search_index = false
generate_feed = true
feed_filename = "rss.xml"

minify_html = true

taxonomies = [
  { name = "tags", feed = false },
]

[languages.no]
title = "Tim Hårek"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = 'one-dark'
external_links_target_blank = true
external_links_no_referrer = true
smart_punctuation = true

[extra]
author = "Tim Hårek Andreassen"
email = "tim@harek.dev"
date_format = "%Y-%m-%d"
date_format__updated = "%Y-%m-%d"
logo = "img/logo.svg"
cover = "img/cover.png"

nav = [
  { name = "Blog", path = "/blog" },
  { name = "Connect", path = "/connect" },
  { name = "About", path = "/about" },
]

footer_nav = [
  { name = "Privacy", path = "/privacy" },
  { name = "RSS", path = "/rss.xml" }
]

