base_url = "https://timharek.no"

title = "Tim Hårek"
description = """
Full-stack developer from Norway that cares about creating solutions that
respects people in terms of privacy, security and user experience."""

default_language = "en"

compile_sass = true
build_search_index = false
generate_feed = true
feed_filename = "rss.xml"

minify_html = true

taxonomies = [
  { name = "tags", feed = false },
]

[languages.no]
title = "Tim Hårek"

[markdown]
highlight_code = true
highlight_theme = "one-dark"
external_links_target_blank = true
external_links_no_referrer = true
smart_punctuation = true

[extra]
author = "Tim Hårek Andreassen"
author_img = "img/me.jpeg"
email = "tim@harek.no"
date_format = "%Y-%m-%d"
date_format__updated = "%Y-%m-%d"
logo = "img/logo.svg"
cover = "img/cover.png"

nav = [
  { name = "Blog", path = "@/blog/_index.md" },
  { name = "Work", path = "@/work/_index.md" },
  { name = "Connect", path = "@/connect/_index.md" },
  { name = "About", path = "@/about/_index.md" },
]

footer_nav = [
  { name = "Stats", path = "@/stats.md" },
  { name = "Privacy", path = "@/privacy.md" },
  { name = "RSS", path = "/rss.xml" }
]

