# The URL the site will be built for
base_url = "https://timharek.no"

title = "Tim Hårek"
description = """
I'm a developer from Norway. I care about creating solutions that respects
people in terms of privacy, security and user experience.
This is my corner on the interwebs, have a look around."""

default_language = "en"

compile_sass = true
build_search_index = true
generate_feed = true
feed_filename = "rss.xml"

minify_html = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = 'one-dark'
external_links_target_blank = true
external_links_no_referrer = true
smart_punctuation = true

[extra]
primary_color = "0096F5"
author = "Tim Hårek Andreassen"
email = "tim@harek.dev"
date_format = "%B %e, %Y"

nav = [
  { name = "About", path = "/about" },
  { name = "Blog", path = "/blog" },
  { name = "CV", path = "/cv" },
]

footer = [
  { name = "Uses", path = "/uses" },
  { name = "Privacy", path = "/privacy" },
  { name = "Photos", path = "https://photos.timharek.no" },
]
