last_update = 2024-05-08

[basics]
name = "Tim Hårek Andreassen"
label = "Software engineer"
image = "https://timharek.no/.well-known/avatar"
email = "tim@harek.no"
phone = "+47 400 43 672"
url = "https://timharek.no"
summary = """
I'm Tim Hårek Andreassen, a technologist from the west-coast of Norway that
likes to write about my learnings, design, programming, logging, note-taking and
so on… I care about creating solutions that respects people's privacy, security
and user experience. I have a bachelors degree in informatics, specifically
Computer Security. Presently I'm working as a software engineer at Value
Technology, and I'm also an IT manager for an offshore-service company, Vest
Kontakt.
"""

[basics.location]
city = "Bergen"
countryCode = "NO"

[[basics.profiles]]
network = "GitHub"
username = "timharek"
url = "https://github.com/timharek"

[[basics.profiles]]
network = "SourceHut"
username = "timharek"
url = "https://sr.ht/timharek"

[[basics.profiles]]
network = "Printables"
username = "timharek"
url = "https://www.printables.com/@timharek"

[[work]]
name = "Value Technology"
position = "Software engineer & partner"
url = "https://valuegroup.no"
startDate = 2023-08-07
highlights = [
  "Full-stack Node- and Deno-applications.",
  "Managing and automating infrastructure running in Google Cloud Platform.",
  "Maintaining and designing full-stack applications.",
  "Integrate with different ERP- and accounting-solutions.",
  "Normalize data with Raw technologies.",
  "Develop and maintain Value 360 using modern technologies and practices."
]

[[work]]
name = "Netlife Bergen"
position = "Technologist"
url = "https://netlife.com"
startDate = 2021-08-02
endDate = 2023-08-04
highlights = [
  "Tech lead in multiple projects.",
  "Held internal workshops.",
  "Held presentations about technology and UX at the University of Bergen.",
  "Full-stack development with Craft CMS, Sanity CMS, Next.js, Vue.js and Deno.",
  "Mentored new developers.",
]

[[work]]
name = "Vest Kontakt"
position = "IT Manager"
url = "https://vestkontakt.no"
startDate = 2012-12-24
highlights = [
  "Digitalized manual processes, eg. CRM, accouting software, etc.",
  "Provided IT support for employees, remote and on-site.",
  "Re-designed website, using modern technologies and deployment.",
  "Automated parts of the annual inventory routine.",
]

[[work]]
name = "Freelance"
position = "Full-stack developer"
startDate = 2021-04-19
endDate = 2021-07-16
highlights = [
  "Worked for Netlife Bergen.",
  "Development on KHdele's website.",
  "Development on One Ocean Expedtion's website.",
]

[[work]]
name = "University of Bergen"
url = "https://uib.no"
position = "IT assistent"
startDate = 2018-08-12
endDate = 2021-06-30
highlights = [
  "Provided technical support for students and lecturers.",
  "Part-time job beside my bachelors-degree.",
]
hide = true

[[work]]
name = "InfoCare"
url = "https://infocare.no"
position = "Technician (Summer job)"
startDate = 2020-06-18
endDate = 2020-08-03
highlights = [
  "Computer-repair of Dell and Lenovo computers, both laptops and desktops.",
  "IT support at ABB Bergen, Kokstad.",
]
hide = true

[[work]]
name = "Appex"
url = "https://appex.no"
position = "Developer (Summer intern)"
startDate = 2019-06-17
endDate = 2019-08-05
highlights = [
  "Pilot project Sildikon Valley 2019, in Haugesund.",
  "Developed a cross-platform AR-app for a local real-estate company.",
]

[[work]]
name = "PSS Securitas"
position = "Security Guard"
startDate = 2017-10-15
endDate = 2018-11-10
highlights = [
  "Responsible for maintaining Norwegian alcohol laws.",
  "Part-time job as a bouncer beside my studies in Bergen.",
]
hide = true

[[work]]
name = "Forsvaret"
url = "https://forsvaret.no"
position = "Guard Commander"
startDate = 2015-09-21
endDate = 2016-09-23
highlights = [
  "Compulsory military service stationed at Ulsnes, Hundvåg, Stavanger.",
  "Responsible for seven other soldiers.",
]
hide = true

[[volunteer]]
name = "friByte"
url = "https://fribyte.no"
position = "Member"
startDate = 2020-09-08
endDate = 2024-04-09
highlights = [
  "Maintenance and operation of IT systems for student organizations in Bergen.",
  "Set up of different services for automatic deployment of other services.",
  "Configuring a easy to maintain script for checking server availability.",
  "Set up Mattermost, moderating channels and maintaining channel workflows.",
  "Initiate Ansible-workflow for maintaining servers.",
]

[[volunteer]]
name = "friByte"
url = "https://fribyte.no"
position = "Leader"
startDate = 2021-01-23
endDate = 2021-12-31
highlights = [
  "Administrative tasks, convene meetings etc.",
  "Re-designed the current website website.",
  "Restructured some of the server-infrastructure.",
  "Simplified how the organization operates and responds to inquires.",
]

[[volunteer]]
name = "Studentradioen i Bergen"
url = "https://srib.no"
position = "Web developer"
startDate = 2020-02-12
endDate = 2021-05-29
highlights = ["Contributed on the development on their new website."]

[[education]]
institituon = "University of Bergen"
url = "https://uib.no"
area = "Computer Security"
studyType = "Bachelor"
startDate = 2017-08-14
endDate = 2021-06-07
courses = ["INF100 - Introduction to programming"]
summary = "Computer Science with a security focus."

[[certificates]]
name = "Relasjonskompetanse for rådgivere og ledere"
date = 2022-11-22
issuer = "Prosessarbeid AS (Målfrid J. Ågotnes)"


[[skills]]
name = "Programming langauges"
keywords = ["Java", "C#", "Python", "HTML", "CSS", "JavaScript", "PHP", "SQL"]

[[skills]]
name = "Libraries and frameworks"
keywords = [
  "Fresh",
  "Deno",
  "Express.js",
  "Jekyll",
  "Next.js",
  "Node.js",
  "React.js",
  "Tailwind",
  "Vue.js",
  "Zola",
  "jQuery",
  "Oak",
  "Zod"
]

[[skills]]
name = "Tools"
keywords = ["Ansible", "Docker", "Git", "Helix", "UNIX", "Vim", "SQLite", "PostgreSQL", "MariaDB/MySQL"]

[[skills]]
name = "Cloud infrastructure"
keywords = ["AWS Amplify", "Azure", "Google Cloud Platform"]

[[skills]]
name = "CI/CD"
keywords = ["GitHub Actions", "GitLab CI/CD", "Buddy.works", "SourceHut builds"]

[[skills]]
name = "Platforms"
keywords = ["Craft CMS", "Sanity", "WordPress", "Joomla", "HubSpot CMS"]

[[skills]]
name = "Design tools"
keywords = ["Affinity Designer", "Adobe CC", "Sketch", "Figma"]

[[languages]]
language = "Norwegian"
fluency = "Native speaker"

[[languages]]
language = "English"
fluency = "Fluent"

[[interests]]
name = "Hiking"
keywords = ["mountains"]

[[interests]]
name = "3D printing"
keywords = ["DIY", "Tool-making"]

[[interests]]
name = "Home Automation"
keywords = ["Home Assistant", "Zigbee", "Raspberry Pi"]

[[projects]]
name = "sticos.no"
client = "Sticos"
url = "https://sticos.no"
roles = ["Tech lead"]
description = "New website made with HubSpot CMS for an Norwegian SaaS company."
startDate = 2022-12-05
endDate = 2023-04-14
keywords = ["HubSpot CMS", "Netlife", "Tailwind", "Website", "Work"]

[[projects]]
name = "valuegroup.no"
client = "Value Group"
url = "https://valuegroup.no"
roles = ["Tech lead"]
description = "New website made with HubSpot CMS for an accounting agency."
startDate = 2022-10-10
endDate = 2022-12-06
keywords = ["HubSpot CMS", "Netlife", "Website", "Work"]

[[projects]]
name = "ren.no"
client = "REN"
url = "https://ren.no"
roles = ["UX-designer"]
description = "Designed components for their internal datasheet creation."
startDate = 2022-05-23
endDate = 2022-09-30
keywords = ["Figma", "Netlife", "Website", "UX", "Work"]

[[projects]]
name = "ypper.no"
client = "Ypper"
url = "https://ypper.no"
roles = ["Tech lead"]
description = "Developed a new website with Ghost CMS with memberships and payment model."
startDate = 2022-02-21
endDate = 2022-04-21
keywords = ["Ghost CMS", "Netlife", "Website", "Tailwind", "Work"]

[[projects]]
name = "Upgrade kolibricarf.no"
client = "Kolibri CARF"
url = "https://kolibricarf.no/"
roles = ["Developer"]
description = "Upgrade website from Craft CMS 2 to Craft CMS 3 including migration of plugins and new setup for donations."
startDate = 2022-06-27
endDate = 2022-07-08
keywords = ["Website", "Craft CMS", "Upgrade", "Netlife", "Work"]

[[projects]]
name = "viljareiser.no"
client = "Vilja"
url = "https://viljareiser.no/"
roles = ["Tech lead", "Developer", "UX designer"]
description = "Developed a new website for a traveling agency with API-integration to their exisiting booking system. Built with Craft CMS 3."
startDate = 2022-01-03
endDate = 2022-06-26
keywords = ["Website", "Craft CMS", "Tailwind", "API", "Netlife", "Work"]

[[projects]]
name = "Frontend and UX assistance"
client = "Ambita"
roles = ["Tech lead", "Developer"]
description = "Assiting the client with developing a new frontend using Vue3 and other modern frontend-frameworks."
startDate = 2021-10-04
endDate = 2022-09-01
keywords = ["Vue", "Netlife", "Work"]

[[projects]]
name = "oneoceanexpedition.com"
client = "Statsraad Lehmkuhl"
url = "https://oneoceanexpedition.com/"
roles = ["Developer"]
description = "A website built with Next.js using API from Havforskningsinstituttet with live-data coming from a sea vessal."
startDate = 2021-05-31
endDate = 2021-09-22
keywords = [
  "Website",
  "Sanity",
  "Tailwind",
  "Mapbox",
  "Next.js",
  "API",
  "Netlife",
  "Work"
]

[[projects]]
name = "Optimze handelensmiljofond.no"
client = "Handelens Miljøfond"
url = "https://handelensmiljofond.no/"
roles = ["Developer"]
description = "Optimize website, reduced page-sizes from ~18 MB down to ~1.2 MB."
startDate = 2021-10-18
endDate = 2021-10-21
keywords = ["Website", "Craft CMS", "Optimze", "Netlife", "Work"]

[[projects]]
name = "verdighetsenteret.no"
client = "Verdighetsenteret"
url = "https://verdighetsenteret.no/"
roles = ["Developer"]
description = "Assisted other developers with development of new webiste."
startDate = 2021-09-01
endDate = 2021-09-14
keywords = ["Website", "Craft CMS", "Tailwind", "Netlife", "Work"]

[[projects]]
name = "Upgrade vff.no"
client = "Verdipapirfondenes forening"
url = "https://vff.no/"
roles = ["Developer"]
description = "Upgraded from Craft CMS v2 to v3. Developed custom Craft CMS-modules for getting data from the official Norwegian fond-register."
startDate = 2021-06-28
endDate = 2021-07-14
keywords = ["Website", "Craft CMS", "Upgrade", "Netlife", "Work"]

[[projects]]
name = "khdele.no"
client = "Høgskulen i Volda"
url = "https://khdele.no/"
roles = ["Developer"]
description = "My first project at Netlife Bergen. We developed a new website for Arts and Crafts for teach-students."
startDate = 2021-04-28
endDate = 2021-06-14
keywords = ["Website", "Craft CMS", "Tailwind", "Netlife", "Work"]

[[projects]]
name = "wcarbon module"
url = "https://jsr.io/@timharek/wcarbon"
description = "Access Website Carbon's API with Deno."
startDate = 2022-06-26
keywords = ["Tool", "CLI", "Deno", "API", "Personal", "Open source"]
sources = ["https://github.com/timharek/wcarbon"]

[[projects]]
name = "d-yr module"
url = "https://jsr.io/@timharek/dyr"
description = "Access Yr.no's weather API with Deno."
startDate = 2022-03-07
keywords = ["Tool", "CLI", "Deno", "API", "Personal", "Open source"]
sources = ["https://github.com/timharek/d-yr"]

[[projects]]
name = "everyday-privacy.com"
url = "https://everyday-privacy.com"
description = "Educate people about privacy and security with an interactive static-site."
startDate = 2021-02-11
endDate = 2023-03-03
keywords = ["Website", "Privacy", "Personal", "Open source"]
sources = ["https://github.com/timharek/everyday-privacy"]

[[projects]]
name = "5545.no"
url = "https://5545.no"
description = "Weather website for a local zip-code in Norway, built with Svelte using Yr's API. "
startDate = 2021-05-03
endDate = 2022-05-28
keywords = ["Website", "API", "Svelte", "Personal", "Tailwind", "Open source"]
sources = ["https://github.com/timharek/5545.no-svelte"]

[[projects]]
name = "sbanken.sh"
description = "Shell-script with options to access Sbanken and see your banking details."
startDate = 2021-11-15
endDate = 2022-08-05
keywords = ["API", "Shell", "Personal", "Open source"]
sources = ["https://github.com/timharek/sbanken.sh"]

[[projects]]
name = "fribyte.no"
client = "friByte"
url = "https://fribyte.no"
description = "Static generated website made with Zola."
startDate = 2021-02-06
endDate = 2023-10-04
keywords = ["Website", "Zola", "Open source"]
sources = ["https://github.com/fribyte-code/fribyte.no"]

[[projects]]
name = "vestkontakt.no"
client = "Vest Kontakt"
url = "https://vestkontakt.no"
roles = ["Developer"]
description = "Static generated website made with Jekyll."
startDate = 2021-01-07
endDate = 2021-02-22
keywords = ["Website", "Jekyll"]

[[projects]]
name = "omdb module"
url = "https://jsr.io/@timharek/omdb"
description = "Access OMDb's API for getting details about movies and TV shows with Deno."
startDate = 2022-06-23
keywords = ["Tool", "CLI", "Deno", "API", "Personal", "Open source"]
sources = [
  "https://github.com/timharek/deno-omdb",
  "https://git.sr.ht/~timharek/deno-omdb",
]

[[projects]]
name = "openlibrary module"
url = "https://jsr.io/@timharek/openlibrary"
description = "Access OpenLibrary's API with Deno."
startDate = 2023-01-15
keywords = ["Tool", "CLI", "Deno", "API", "Personal", "Open source"]
sources = [
  "https://github.com/timharek/deno-books",
  "https://git.sr.ht/~timharek/deno-books",
]

[[projects]]
name = "linkding module"
url = "https://jsr.io/@timharek/linkding"
description = "Access your Linkding instance's API with Deno."
startDate = 2022-11-28
keywords = ["Tool", "CLI", "Deno", "API", "Personal", "Open source"]
sources = [
  "https://github.com/timharek/deno-linkding",
  "https://git.sr.ht/~timharek/deno-linkding",
]

[[projects]]
name = "Web daemon"
client = "Institutt for Journalistikk"
roles = ["Tech lead"]
description = "Developed a web daemon that listens to a webhook from an LMS that updates an old MS-SQL database made in the late 90s. Also made the daemon to be scalable to a full-fledged front-end API for future use."
startDate = 2022-12-06
endDate = 2023-02-27
keywords = ["API", "Database", "Node.js", "Express.js", "TypeScript", "Netlife", "Work"]

[[projects]]
name = "Hima"
url = "https://sr.ht/~timharek/hima"
description = "Home Inventory system built with Deno Fresh using PocketBase as a backend."
startDate = 2023-03-05
keywords = [
  "API",
  "Database",
  "Deno",
  "Personal",
  "PocketBase",
  "Tailwind",
  "TypeScript",
  "Open source"
]
sources = ["https://git.sr.ht/~timharek/hima"]

[[projects]]
name = "filmpolitiet-api"
url = "https://filmpolitiet.wyd.no"
description = "API for NRK P3 Filmpolitiet's reviews. Made using Deno, Fresh and SQLite."
startDate = 2023-05-31
keywords = [
  "API",
  "Database",
  "Deno",
  "Personal",
  "SQLite",
  "Tailwind",
  "TypeScript",
  "Open source"
]
sources = ["https://git.sr.ht/~timharek/filmpolitiet-api"]

[[projects]]
name = "Integrate Front Systems with Raw"
client = "Raw Technologies"
roles = ["Developer"]
description = "Integrate Front Systems sales items into Raw."
startDate = 2024-01-08
endDate = 2024-02-12
keywords = ["Value", "Integration", "Raw", "Work"]

[[projects]]
name = "Integrate Tripletex with Raw"
client = "Raw Technologies"
roles = ["Developer"]
description = "Integrate Tripletex's general ledger into Raw."
startDate = 2023-10-01
endDate = 2024-01-14
keywords = ["Value", "Integration", "Raw", "Work"]

[[projects]]
name = "Integrate Voss of Norway with Raw"
client = "Voss of Norway"
roles = ["Developer"]
description = "Integrate Voss of Norway's general ledger and work orders from Business Central into Raw."
startDate = 2023-09-01
endDate = 2024-01-14
keywords = ["Value", "Integration", "Raw", "Work"]

[[projects]]
name = "europan.no"
client = "Europan Norway"
url = "https://europan.no/"
roles = ["Tech lead", "Developer"]
description = "New website for Europan Norway, a competition for architects."
startDate = 2023-04-28
endDate = 2023-08-04
keywords = ["Website", "Craft CMS", "Tailwind", "Netlife", "Work"]

[[projects]]
name = "Value 360"
client = "Value Group"
roles = ["Tech lead", "Developer"]
description = "Quality assurance system for agencies. Automating tasks and routines for accountants and team leaders."
startDate = 2023-02-28
keywords = [
  "API",
  "PostgreSQL",
  "Prisma",
  "GCP",
  "MUI",
  "Netlife",
  "Next.js",
  "Tailwind",
  "Value",
  "Website",
  "Work"
]

[[projects]]
name = "API client"
client = "Gaitline"
roles = ["Tech lead", "Developer"]
description = "API client interacting with multiple APIs. Writing EDIFACT files via email and SFTP."
startDate = 2023-01-24
endDate = 2023-05-16
keywords = ["API", "Deno", "GCP", "Netlife", "Oak", "Value", "Work"]

[[projects]]
name = "Bergen Open Source Website"
client = "friByte"
url = "https://boskonf.no"
roles = ["Developer"]
description = "Website for friByte's Open Source conference."
startDate = 2023-09-20
endDate = 2023-11-05
keywords = ["Zola", "Website", "Open source"]
sources = ["https://github.com/fribyte-code/boskonf.no/"]

