image: alpine/edge
packages:
  - deno
  - rsync
environment:
  deploy: tim@vps.tukler.no
secrets:
  - 0323bc6f-a046-4b96-8496-2bac6e7ee107
sources:
  - git@git.sr.ht:~timharek/timharek.no
triggers:
  - action: email
    condition: failure
    to: tim@harek.no
tasks:
  - test: |
      cd timharek.no
      deno test -A
      deno task check
  - check: |
      cd timharek.no
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - mirror: |
      cd timharek.no
      git remote add github git@github.com:timharek/timharek.no.git
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git push -f github main
  - deploy: |
      cd timharek.no
      git --no-pager log -1 --format=%ci > last_deploy
      sshopts="ssh -o StrictHostKeyChecking=no"
      rsync --rsh="$sshopts" -avrP --exclude "last_deploy" --exclude "node_modules" --exclude ".env*" --delete . $deploy:/var/www/timharek.no
      rsync --rsh="$sshopts" -avrP last_deploy $deploy:/var/www/timharek.no/last_deploy

