image: alpine/edge
packages:
  - rsync
environment:
  deploy: tim@vps.tukler.no
secrets:
  - 0323bc6f-a046-4b96-8496-2bac6e7ee107
sources:
  - git+ssh://git@git.sr.ht/~timharek/timharek.no
triggers:
  - action: email
    condition: failure
    to: tim@harek.no
tasks:
  - check: |
      cd timharek.no
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
      zola check
  - mirror: |
      cd timharek.no
      git remote add github git@github.com:timharek/timharek.no.git
      git remote add codeberg git@codeberg.org:timharek/timharek.no.git
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      ssh-keyscan -t rsa codeberg.org >> ~/.ssh/known_hosts
      git push -f github main
      git push -f codeberg main
  - deploy: |
      cd timharek.no
      sshopts="ssh -o StrictHostKeyChecking=no"
      rsync --rsh="$sshopts" -avrP . $deploy:/var/www/timharek.no

