[[projects]]
name = "fribyte.no"
description = "Re-design of friByte's website. Built with Jekyll."
date = 2021-05-16
logo = "img/resume/fribyte.svg"
link = "https://fribyte.no"

[[projects]]
name = "vestkontakt.no"
description = "Re-design of Vest Kontakt AS's website."
date = 2021-02-13
logo = "img/projects/vk.svg"
link = "https://vestkontakt.no"

[[projects]]
name = "p-yr"
description = "Simple Python-script for weather, using yr.no's API"
date = 2021-02-04
logo = "img/projects/p-yr.svg"
sourcecode = "https://github.com/timharek/p-yr"

[[projects]]
name = "5545.no"
description = "Weather app for a local ZIP code in Norway, built with Vue.js."
date = 2020-04-27
logo = "img/projects/5545.svg"
link = "https://5545.no"
sourcecode = "https://github.com/timharek/5545.no"

[[projects]]
name = "Everyday Privacy"
description = "Open source project for educating people about online privacy and security."
date = 2021-06-12
link = "https://everyday-privacy.com"
logo = "img/projects/everyday-privacy.svg"
sourcecode = "https://github.com/timharek/everyday-privacy"
