last_update = 2021-06-08
name = "Tim Hårek Andreassen"
tldr = "I'm a developer from the west coast of Norway. I care about creating solutions that respects people, in terms of privacy, security and user experience. I have a bachelors degree in informatics, specifically Computer Security. Presently I'm self-employed, working as a freelance developer for Netlife Design Bergen, and also assisting an offshore-service company, Vest Kontakt, providing technical support."

[[work]]
name = "TH Andreassen"
glyph = "img/symbol.svg"

  [[work.role]]
  name = "Freelance developer"
  present = true
  start = 2021-04-19
  desc = [
  "Working for Netlife Design Bergen.",
  "Development of KHdele's new website.",
  "Development of One Ocean Expedtion's new website."
]

[[work]]
name = "Vest Kontakt AS"
glyph = "img/resume/vk.svg"

  [[work.role]]
  name = "IT Manager"
  present = true
  start = 2012-12-24
  desc = [
  "Setup and maintenance of IT systems, i.e. CRM, accounting software, etc.",
  "IT support for employees, both remote and on-site.",
  "Re-designed their website, with modern technologies.",
  "Created a more efficient system for their annual inventory."
]

[[work]]
name = "University of Bergen"
glyph = "img/resume/uib.svg"

  [[work.role]]
  name = "IT assistent"
  present = false
  start = 2018-08-12
  end = 2021-06-30
  desc = [
  "Technical support for students and lectures.",
  "Part-time job beside my bachelors-degree."
]

[[work]]
name = "InfoCare Norge AS"
glyph = "img/resume/infocare.svg"

  [[work.role]]
  name = "Technician (Summer job)"
  present = false
  start = 2020-06-18
  end = 2020-08-03
  desc = [
  "Computer-repair of Dell and Lenovo computers, both laptops and desktops.",
  "IT support at ABB Bergen Kokstad."
]

[[work]]
name = "Appex"
glyph = "img/resume/appex.svg"

  [[work.role]]
  name = "Developer (Summer intern)"
  present = false
  start = 2019-06-17
  end = 2019-08-05
  desc = [
  "Pilot project Sildikon Valley 2019 in Haugesund.",
  "Developed a cross-platform AR-app for a local real-estate company."
]

[[voluntary]]
name = "Studentradioen i Bergen"
glyph = "img/resume/srib.svg"

  [[voluntary.role]]
  name = "Web developer"
  start = 2020-02-12
  end = 2021-05-29
  desc = [
  "Contributed on the development of their new website, using modern technologies."
]

[[voluntary]]
name = "friByte"
glyph = "img/resume/fribyte.svg"

  [[voluntary.role]]
  name = "Member"
  start = 2020-09-08
  end = 2021-01-23
  desc = [
  "Maintenance and operation of IT systems for student organizations in Bergen."
]

  [[voluntary.role]]
  name = "Leader"
  start = 2021-01-23
  desc = [
  "Administrative tasks, convene meetings etc.",
  "Re-designed their website.",
  "Currently restructuring their server-infrastructure."
]

[[education]]
name = "University of Bergen"
glyph = "img/resume/uib.svg"

  [[education.role]]
  name = "Bachelor in Computer Security"
  start = 2017-08-14
  end = 2021-06-07
  desc = [
  "A bachelors degree in Computer Science with an extra emphasis on security."
]

[[skills]]
name = "Programming languages"
list = [ "Java", "C#", "Python", "HTML", "(S)CSS", "JS", "Liquid", "Tera" ]

[[skills]]
name = "Libraries and frameworks"
list = [ "Node.js", "jQuery", "React.js","Vue.js", "Jekyll", "Zola" ]

[[skills]]
name = "Tools"
list = [ "Git", "Vim", "UNIX" ]

[[skills]]
name = "Platforms"
list = [ "Craft CMS", "Sanity CMS", "WordPress", "Joomla" ]

[[skills]]
name = "Design"
list = [ "Affinity Designer", "Adobe CC", "Sketch", "Figma" ]

